name: minecraft-server
displayName: Minecraft 服务器
description: 管理 Minecraft 服务器、线路与周目，展示在线状态和玩家统计。
icon: i-ri:server-line
main: online.yudream.base.plugin.minecraft.bootstrap.MinecraftServerPlugin
version: 1.3.1
softdepend:
  - yudream-wallet
  - yudream-skin
