import type { YuDreamPluginSdk } from '@yudream/plugin-sdk'
import type { AgentProposal, AgentSession, CardTemplate, CrawlJob, DeliveryRecord, GroupBinding, Option, PageResult, ParseRules, Site, TemplateDraftPreviewRequest, TemplateDraftPreviewResult, TemplateVersion, WorkspacePlan } from '../types'
export function createWebCardApi(sdk: YuDreamPluginSdk) {
  const q = (page = 1, size = 10) => `?page=${page}&size=${size}`
  return {
    sites: (page=1,size=10)=>sdk.http.get<PageResult<Site>>(`/admin/sites${q(page,size)}`),
    site: (id:string)=>sdk.http.get<{site:Site;headers:Record<string,string>}>(`/admin/sites/${encodeURIComponent(id)}`),
    saveSite: (site:Site,headers?:Record<string,string>)=>sdk.http.request<Site>('/admin/sites',{method:'POST',data:{site,headers}}),
    deleteSite: (id:string)=>sdk.http.request(`/admin/sites/${encodeURIComponent(id)}`,{method:'DELETE'}),
    rules: (id:string)=>sdk.http.get<ParseRules|null>(`/admin/sites/${encodeURIComponent(id)}/parse-rules`),
    saveRules: (id:string,rules:ParseRules)=>sdk.http.request<ParseRules>(`/admin/sites/${encodeURIComponent(id)}/parse-rules`,{method:'PUT',data:rules}),
    testFetch: (id:string,url:string)=>sdk.http.request<Record<string,unknown>>(`/admin/sites/${encodeURIComponent(id)}/test-fetch`,{method:'POST',data:{url}}),
    testParse: (id:string,url:string)=>sdk.http.request<Record<string,unknown>>(`/admin/sites/${encodeURIComponent(id)}/test-parse`,{method:'POST',data:{url}}),
    previewUrl: (url:string)=>sdk.http.request<{base64:string;fields:Record<string,unknown>;site:string;finalUrl:string;templateVersionId:string}>('/admin/link-preview',{method:'POST',data:{url}}),
    previewDraft: (value:TemplateDraftPreviewRequest)=>sdk.http.request<TemplateDraftPreviewResult>('/admin/template-draft-preview',{method:'POST',data:value}),
    templates: (page=1,size=10)=>sdk.http.get<PageResult<CardTemplate>>(`/admin/templates${q(page,size)}`),
    template: (id:string)=>sdk.http.get<CardTemplate>(`/admin/templates/${encodeURIComponent(id)}`),
    saveTemplate: (value:CardTemplate)=>sdk.http.request<CardTemplate>('/admin/templates',{method:'POST',data:value}),
    deleteTemplate: (id:string)=>sdk.http.request(`/admin/templates/${encodeURIComponent(id)}`,{method:'DELETE'}),
    saveVersion: (value:TemplateVersion)=>sdk.http.request<TemplateVersion>('/admin/template-versions',{method:'POST',data:value}),
    version: (id:string)=>sdk.http.get<TemplateVersion>(`/admin/template-versions/${encodeURIComponent(id)}`),
    versions: (id:string,page=1,size=10)=>sdk.http.get<PageResult<TemplateVersion>>(`/admin/templates/${encodeURIComponent(id)}/versions${q(page,size)}`),
    preview: (id:string,fixture:Record<string,unknown>)=>sdk.http.request<{base64:string;version:TemplateVersion}>(`/admin/template-versions/${encodeURIComponent(id)}/preview`,{method:'POST',data:{fixture}}),
    publish: (id:string,versionId:string)=>sdk.http.request<CardTemplate>(`/admin/templates/${encodeURIComponent(id)}/publish`,{method:'POST',data:{versionId}}),
    rollback: (id:string,versionId:string)=>sdk.http.request<TemplateVersion>(`/admin/templates/${encodeURIComponent(id)}/rollback`,{method:'POST',data:{versionId}}),
    bindings: (page=1,size=10)=>sdk.http.get<PageResult<GroupBinding>>(`/admin/group-bindings${q(page,size)}`),
    saveBinding: (value:GroupBinding)=>sdk.http.request<GroupBinding>('/admin/group-bindings',{method:'POST',data:value}),
    deleteBinding: (id:string)=>sdk.http.request(`/admin/group-bindings/${encodeURIComponent(id)}`,{method:'DELETE'}),
    jobs: (page=1,size=10)=>sdk.http.get<PageResult<CrawlJob>>(`/admin/crawl-jobs${q(page,size)}`),
    saveJob: (value:CrawlJob)=>sdk.http.request<CrawlJob>('/admin/crawl-jobs',{method:'POST',data:value}),
    deleteJob: (id:string)=>sdk.http.request(`/admin/crawl-jobs/${encodeURIComponent(id)}`,{method:'DELETE'}),
    deliveries: (page=1,size=10)=>sdk.http.get<PageResult<DeliveryRecord>>(`/admin/deliveries${q(page,size)}`),
    retry: (id:string)=>sdk.http.request<DeliveryRecord>(`/admin/deliveries/${encodeURIComponent(id)}/retry`,{method:'POST'}),
    sessions: (page=1,size=10)=>sdk.http.get<PageResult<AgentSession>>(`/admin/agent-sessions${q(page,size)}`),
    createSession: (value:AgentSession)=>sdk.http.request<AgentSession>('/admin/agent-sessions',{method:'POST',data:value}),
    deleteSession: (id:string)=>sdk.http.request(`/admin/agent-sessions/${encodeURIComponent(id)}`,{method:'DELETE'}),
    startAgentMessage: (id:string,message:string)=>sdk.http.post<{streamId:string}>(`/admin/agent-sessions/${encodeURIComponent(id)}/messages/stream`,{message}),
    agentMessageEventsUrl: (streamId:string)=>sdk.http.url(`/admin/agent-message-streams/${encodeURIComponent(streamId)}/events`),
    /** @deprecated The Studio page uses startAgentMessage; retained for the legacy management route. */
    agentMessage: (id:string,message:string)=>sdk.http.request<AgentProposal>(`/admin/agent-sessions/${encodeURIComponent(id)}/messages`,{method:'POST',data:{message}}),
    proposals: (page=1,size=10)=>sdk.http.get<PageResult<AgentProposal>>(`/admin/agent-proposals${q(page,size)}`),
    updateProposal: (id:string,plan:WorkspacePlan)=>sdk.http.request<AgentProposal>(`/admin/agent-proposals/${encodeURIComponent(id)}`,{method:'PUT',data:{plan}}),
    applyProposal: (id:string)=>sdk.http.request<TemplateVersion>(`/admin/agent-proposals/${encodeURIComponent(id)}/apply`,{method:'POST'}),
    rejectProposal: (id:string)=>sdk.http.request<AgentProposal>(`/admin/agent-proposals/${encodeURIComponent(id)}/reject`,{method:'POST'}),
    connections: ()=>sdk.http.get<Option[]>('/admin/options/connections'),
    groups: (connectionId:string)=>sdk.http.get<Option[]>(`/admin/options/groups?connectionId=${encodeURIComponent(connectionId)}`),
    agents: ()=>sdk.http.get<Option[]>('/admin/options/ai-agents'),
  }
}
