name: yudream-wallet
displayName: 用户钱包
description: 管理余额、积分、充值、转账和资产流水。
icon: i-ri:wallet-3-line
main: online.yudream.base.plugin.wallet.bootstrap.WalletPlugin
version: 1.1.5
softdepend:
  - yudream-skin
