<script setup lang="ts">
import { FaButton, FaDrawer, FaTag } from '@yudream/components'
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { jobVersionLabel } from '../types'
import type { WikiJob, WikiJobEvent } from '../types'
const props = defineProps<{ modelValue: boolean; job: WikiJob | null; api: { jobEventsUrl(streamId: string): string; pauseJob(jobId: string): Promise<WikiJob>; resumeJob(jobId: string): Promise<WikiJob>; cancelJob(jobId: string): Promise<WikiJob>; job(jobId: string): Promise<WikiJob> } }>()
const emit = defineEmits<{ 'update:modelValue': [boolean] }>()
const logs = ref<WikiJobEvent[]>([]); const current = ref<WikiJob | null>(null); let abort: AbortController | undefined
const active = computed(() => current.value && ['PENDING', 'RUNNING', 'CANCELLING'].includes(current.value.status))
function close() { abort?.abort(); abort = undefined; emit('update:modelValue', false) }
async function connect(job: WikiJob) { abort?.abort(); current.value = job; logs.value = []; const controller = new AbortController(); abort = controller; try { const token = localStorage.getItem('token'); const response = await fetch(props.api.jobEventsUrl(job.streamId), { signal: controller.signal, headers: { Accept: 'text/event-stream', ...(token ? { Authorization: token } : {}) } }); if (!response.ok || !response.body) throw new Error(`日志连接失败 (${response.status})`); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; while (!controller.signal.aborted) { const next = await reader.read(); if (next.done) break; buffer += decoder.decode(next.value, { stream: true }); const chunks = buffer.split(/\r?\n\r?\n/); buffer = chunks.pop() || ''; for (const chunk of chunks) { const text = chunk.split(/\r?\n/).filter(line => line.startsWith('data:')).map(line => line.slice(5).trimStart()).join('\n'); if (!text) continue; const event = JSON.parse(text) as WikiJobEvent; current.value = event; logs.value.push(event) } } } catch (error) { if (!controller.signal.aborted) logs.value.push({ ...job, message: error instanceof Error ? error.message : '日志连接中断', level: 'ERROR' }) } }
async function pause() { if (current.value) current.value = await props.api.pauseJob(current.value.jobId) }
async function resume() { if (current.value) current.value = await props.api.resumeJob(current.value.jobId) }
async function cancel() { if (current.value) current.value = await props.api.cancelJob(current.value.jobId) }
watch(() => [props.modelValue, props.job] as const, ([open, job]) => { if (open && job) void connect(job); else if (!open) abort?.abort() }, { immediate: true })
onBeforeUnmount(() => abort?.abort())
</script>
<template><FaDrawer :model-value="modelValue" title="任务日志" side="right" :show-confirm-button="false" :footer="false" content-class="w-[min(760px,calc(100vw-24px))]" @update:model-value="value => !value && close()"><div v-if="current" class="grid gap-4"><div class="flex justify-between"><strong>{{ jobVersionLabel(current.version) }}</strong><FaTag>{{ current.status }}</FaTag></div><div><div class="flex justify-between text-sm"><span>{{ current.phase }}</span><span>{{ current.done }} / {{ current.total }}</span></div><progress class="w-full" :max="Math.max(current.total, 1)" :value="current.done" /></div><div class="flex gap-2"><FaButton v-if="current.status === 'RUNNING'" variant="outline" @click="pause">暂停</FaButton><FaButton v-if="['PAUSED', 'PAUSING'].includes(current.status)" variant="outline" @click="resume">继续</FaButton><FaButton v-if="active" variant="destructive" @click="cancel">取消任务</FaButton><FaButton variant="outline" @click="close">后台运行</FaButton></div><div class="max-h-[50vh] overflow-auto font-mono text-sm"><div v-for="(log,index) in logs" :key="`${log.updatedAt}-${index}`" class="border-b py-2"><strong>{{ log.phase }}</strong> {{ log.message }}</div></div></div></FaDrawer></template>
