<script setup lang="ts">
import type { TableColumn } from '@yudream/components'
import type { MinecraftEndpoint } from '../types'
import type { MinecraftServerPluginModel } from '../composables/useMinecraftServerPlugin'
import { FaButton, FaCard, FaIcon, FaInput, FaNumberField, FaPageHeader, FaPageMain, FaResponsiveTable, FaSelect, FaSwitch, useFaModal, useFaToast } from '@yudream/components'
import MarkdownEditor from '../components/MarkdownEditor.vue'
const props = defineProps<{ model: MinecraftServerPluginModel }>()
const modal = useFaModal()
const toast = useFaToast()
const editionOptions = [{ label: 'Java', value: 'JAVA' }, { label: '基岩版', value: 'BEDROCK' }]
const columns: TableColumn<MinecraftEndpoint>[] = [{ id: 'name', header: '线路名称', width: 160 }, { id: 'host', header: '主机', width: 220 }, { id: 'port', header: '端口', width: 120 }, { id: 'edition', header: '版本', width: 130 }, { id: 'primary', header: '主线', width: 90 }, { id: 'enabled', header: '启用', width: 90 }, { id: 'operation', header: '操作', width: 90, fixed: 'right' }]
function confirmDelete() { const server = props.model.servers.find(item => item.id === props.model.serverForm.id); if (server) modal.confirm({ title: '删除服务器', content: `确认删除“${server.name}”吗？相关状态、周目操作和玩家记录也会删除。`, onConfirm: () => props.model.deleteServer(server) }) }
async function uploadMap(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; try { await props.model.uploadMap(file) } catch (error) { toast.error(error instanceof Error ? error.message : '地图上传失败') } finally { (event.target as HTMLInputElement).value = '' } }
function confirmDeleteMap() { modal.confirm({ title: '删除地图', content: '确认删除此地图 ZIP 附件吗？', onConfirm: () => props.model.deleteMap() }) }
</script>
<template>
  <FaPageHeader :title="model.serverForm.id ? '编辑服务器' : '新增服务器'" class="mb-0" />
  <FaPageMain><form class="grid gap-4" @submit.prevent="model.saveServer">
    <div class="grid grid-cols-1 gap-3 md:grid-cols-[minmax(220px,1fr)_160px_120px]"><label class="grid gap-2"><span>名称</span><FaInput v-model="model.serverForm.name" /></label><label class="grid gap-2"><span>排序</span><FaNumberField v-model="model.serverForm.sort" /></label><label class="grid gap-2"><span>启用</span><FaSwitch v-model="model.serverForm.enabled" /></label></div>
    <div v-if="model.serverForm.id" class="mt-4 grid gap-3 rounded-lg border p-4"><div class="flex flex-wrap items-center justify-between gap-2"><div><h3 class="text-base font-semibold">地图 ZIP</h3><p class="text-sm text-muted-foreground">上传后默认私有；公开地图可由普通用户下载。</p></div><label class="inline-flex cursor-pointer"><input class="sr-only" type="file" accept=".zip,application/zip,application/x-zip-compressed" :disabled="model.mapOperating" @change="uploadMap" /><FaButton as="span" type="button" variant="outline" :loading="model.mapOperating"><FaIcon name="i-ri:upload-2-line" />上传 ZIP</FaButton></label></div><template v-if="model.selectedServer?.map"><div class="mc-map-admin-row"><span>{{ model.selectedServer.map.originalName || '地图 ZIP' }}</span><label class="inline-flex items-center gap-2 text-sm">公开下载 <FaSwitch :model-value="model.selectedServer.map.publicAccess" :disabled="model.mapOperating" @update:model-value="model.setMapPublicAccess(Boolean($event))" /></label><div class="flex gap-2"><FaButton size="sm" type="button" variant="outline" :loading="model.mapOperating" @click="model.downloadMap(true)"><FaIcon name="i-ri:download-line" />下载</FaButton><FaButton size="sm" type="button" variant="destructive" :disabled="model.mapOperating" @click="confirmDeleteMap"><FaIcon name="i-ri:delete-bin-line" />删除</FaButton></div></div></template><p v-else class="text-sm text-muted-foreground">尚未上传地图 ZIP。</p></div>
    <div class="mt-4 grid gap-3"><div class="flex flex-wrap items-center justify-between gap-2"><h3 class="text-base font-semibold">多线路地址</h3><FaButton size="sm" variant="outline" type="button" @click="model.addEndpoint"><FaIcon name="i-ri:add-line" />新增线路</FaButton></div><FaResponsiveTable :row-key="(_row, index) => String(index)" table-root-class="max-w-full overflow-x-auto rounded-lg" table-class="min-w-[980px]" border stripe :columns="columns" :data="model.serverForm.endpoints"><template #cell-name="{ row }"><FaInput v-model="row.original.name" /></template><template #cell-host="{ row }"><FaInput v-model="row.original.host" /></template><template #cell-port="{ row }"><FaInput :model-value="row.original.port ?? ''" @update:model-value="row.original.port = $event" /></template><template #cell-edition="{ row }"><FaSelect v-model="row.original.edition" :options="editionOptions" /></template><template #cell-primary="{ row }"><FaSwitch v-model="row.original.primaryLine" /></template><template #cell-enabled="{ row }"><FaSwitch v-model="row.original.enabled" /></template><template #cell-operation="{ index }"><FaButton size="sm" variant="destructive" type="button" @click="model.removeEndpoint(index)"><FaIcon name="i-ri:delete-bin-line" /></FaButton></template><template #card="{ row, index }"><FaCard class="w-full"><div class="flex flex-col gap-3"><div class="flex items-center justify-between gap-2"><span class="text-base font-semibold">线路名称</span><FaInput v-model="row.name" class="w-36 shrink-0" /></div><div class="flex flex-col gap-2 text-sm"><div class="flex items-center justify-between gap-2"><span class="shrink-0 text-secondary-foreground/60">主机</span><FaInput v-model="row.host" class="w-44 shrink-0" /></div><div class="flex items-center justify-between gap-2"><span class="shrink-0 text-secondary-foreground/60">端口</span><FaInput :model-value="row.port ?? ''" class="w-24 shrink-0" @update:model-value="row.port = $event" /></div><div class="flex items-center justify-between gap-2"><span class="shrink-0 text-secondary-foreground/60">版本</span><FaSelect v-model="row.edition" :options="editionOptions" class="w-28 shrink-0" /></div><div class="flex items-center justify-between gap-2"><span class="shrink-0 text-secondary-foreground/60">主线</span><FaSwitch v-model="row.primaryLine" /></div><div class="flex items-center justify-between gap-2"><span class="shrink-0 text-secondary-foreground/60">启用</span><FaSwitch v-model="row.enabled" /></div></div><div class="flex flex-wrap gap-2 border-t pt-3"><FaButton size="sm" variant="destructive" type="button" @click="model.removeEndpoint(index)"><FaIcon name="i-ri:delete-bin-line" /></FaButton></div></div></FaCard></template></FaResponsiveTable></div>
    <div class="mt-4 grid gap-3"><h3 class="text-base font-semibold">Markdown 描述</h3><MarkdownEditor v-model="model.serverForm.descriptionMarkdown" :upload-image="model.uploadMarkdownImage" /></div><div class="mt-4 flex flex-wrap justify-end gap-2"><FaButton v-if="model.serverForm.id" type="button" variant="destructive" :loading="model.saving" @click="confirmDelete">删除</FaButton><FaButton type="submit" :loading="model.saving"><FaIcon name="i-ri:save-3-line" />保存</FaButton></div>
  </form></FaPageMain>
</template>
